services:
  - type: web
    name: yt-dl-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: starter
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
